/**
 * Demo catalogue used by `npm run seed`.
 * Prices are in INR. Images point at the generated artwork endpoint so the
 * store renders without any binary assets; swap in real CDN URLs any time.
 */

const categories = [
  { name: 'Electronics', description: 'Audio, wearables and smart devices engineered for everyday life.', icon: 'electronics', featured: true, displayOrder: 1 },
  { name: 'Fashion', description: 'Considered essentials and statement pieces in premium fabrics.', icon: 'fashion', featured: true, displayOrder: 2 },
  { name: 'Home & Living', description: 'Objects that make a house feel like home.', icon: 'home', featured: true, displayOrder: 3 },
  { name: 'Beauty & Care', description: 'Clean formulations backed by real clinical results.', icon: 'beauty', featured: true, displayOrder: 4 },
  { name: 'Sports & Outdoors', description: 'Gear that keeps up with every session.', icon: 'sports', featured: true, displayOrder: 5 },
  { name: 'Books & Stationery', description: 'Paper, ink and everything in between.', icon: 'books', featured: false, displayOrder: 6 },
  { name: 'Gaming', description: 'Consoles, controllers and desk setups built to win.', icon: 'gaming', featured: true, displayOrder: 7 },
  { name: 'Cameras', description: 'Capture more with optics and vlogging kits.', icon: 'cameras', featured: false, displayOrder: 8 },
];

const colors = {
  black: 'Midnight Black',
  white: 'Arctic White',
  blue: 'Cobalt Blue',
  green: 'Forest Green',
  grey: 'Graphite Grey',
  sand: 'Desert Sand',
  red: 'Crimson Red',
  navy: 'Navy',
};

const products = [
  {
    name: 'Aurora X2 Wireless Headphones',
    brand: 'Auralis',
    category: 'Electronics',
    price: 8999,
    discountPrice: 6499,
    stock: 42,
    tags: ['headphones', 'audio', 'anc', 'wireless'],
    badges: ['Best Seller'],
    isFeatured: true,
    shortDescription: 'Hybrid active noise cancelling with 40-hour battery life.',
    description:
      'The Aurora X2 pairs a 40mm beryllium-coated driver with adaptive hybrid ANC that samples your environment 50,000 times a second. Memory-foam earcups wrapped in protein leather keep long sessions comfortable, while multipoint Bluetooth 5.3 lets you jump between laptop and phone without reconnecting.',
    specifications: [
      { key: 'Driver', value: '40mm beryllium-coated dynamic' },
      { key: 'Battery life', value: '40 hours (ANC on)' },
      { key: 'Bluetooth', value: '5.3 with multipoint' },
      { key: 'Codecs', value: 'SBC, AAC, LDAC' },
      { key: 'Weight', value: '268 g' },
      { key: 'Warranty', value: '2 years' },
    ],
    variants: [
      { name: `${colors.black}`, color: colors.black, priceDelta: 0, stock: 18 },
      { name: `${colors.white}`, color: colors.white, priceDelta: 0, stock: 14 },
      { name: `${colors.navy}`, color: colors.navy, priceDelta: 400, stock: 10 },
    ],
  },
  {
    name: 'Pulse Fit 3 Smartwatch',
    brand: 'Kinetiq',
    category: 'Electronics',
    price: 15999,
    discountPrice: 12499,
    stock: 30,
    tags: ['smartwatch', 'fitness', 'wearable'],
    badges: ['Trending'],
    isFeatured: true,
    shortDescription: 'AMOLED health tracking with 14-day battery.',
    description:
      'Track 120+ workout modes, blood oxygen, HRV and sleep stages on a 1.78" always-on AMOLED display. Built-in dual-band GPS keeps pace on trails, and 5ATM water resistance means you can swim in it. Charges to 60% in 25 minutes.',
    specifications: [
      { key: 'Display', value: '1.78" AMOLED, 466x466, 1000 nits' },
      { key: 'Battery', value: 'Up to 14 days typical use' },
      { key: 'Sensors', value: 'SpO2, HR, HRV, skin temperature' },
      { key: 'Water rating', value: '5 ATM' },
      { key: 'GPS', value: 'Dual-band GNSS' },
    ],
    variants: [
      { name: '42mm / Midnight Black', color: colors.black, size: '42mm', stock: 12 },
      { name: '42mm / Desert Sand', color: colors.sand, size: '42mm', stock: 8 },
      { name: '46mm / Graphite Grey', color: colors.grey, size: '46mm', priceDelta: 1500, stock: 10 },
    ],
  },
  {
    name: 'Nimbus Pro Bluetooth Speaker',
    brand: 'Auralis',
    category: 'Electronics',
    price: 5499,
    discountPrice: 4299,
    stock: 55,
    tags: ['speaker', 'audio', 'portable'],
    isNewArrival: true,
    shortDescription: '360° sound with IP67 protection and party link.',
    description:
      'A passive radiator on each side of a 3.5" full-range driver pushes bass well beyond its size. Link up to 100 speakers with PartyLink, drop it in the pool thanks to IP67, and get 24 hours of playback on a single charge.',
    specifications: [
      { key: 'Output', value: '30 W RMS' },
      { key: 'Battery', value: '24 hours' },
      { key: 'Protection', value: 'IP67 dust and water' },
      { key: 'Connectivity', value: 'Bluetooth 5.3, USB-C, AUX' },
    ],
    variants: [
      { name: colors.black, color: colors.black, stock: 25 },
      { name: colors.blue, color: colors.blue, stock: 18 },
      { name: colors.green, color: colors.green, stock: 12 },
    ],
  },
  {
    name: 'Vertex Mechanical Keyboard TKL',
    brand: 'Keyforge',
    category: 'Gaming',
    price: 7499,
    discountPrice: 5999,
    stock: 24,
    tags: ['keyboard', 'mechanical', 'gaming', 'rgb'],
    isFeatured: true,
    shortDescription: 'Hot-swappable gasket mount with per-key RGB.',
    description:
      'A 75% layout with a gasket-mounted aluminium plate for a soft, poppy typing feel. Hot-swap sockets accept any 3- or 5-pin switch, and the CNC aluminium knob controls volume and media. PBT double-shot keycaps resist shine for years.',
    specifications: [
      { key: 'Layout', value: '75% (82 keys), TKL footprint' },
      { key: 'Switches', value: 'Hot-swappable, pre-lubed linear' },
      { key: 'Keycaps', value: 'Double-shot PBT, Cherry profile' },
      { key: 'Connection', value: 'USB-C wired, 1000 Hz polling' },
      { key: 'Extras', value: 'Sound-dampening foam, silicone base' },
    ],
    variants: [
      { name: 'Linear / White', color: colors.white, stock: 10 },
      { name: 'Tactile / Black', color: colors.black, stock: 9 },
      { name: 'Clicky / Blue', color: colors.blue, stock: 5 },
    ],
  },
  {
    name: 'Orbit Wireless Gaming Mouse',
    brand: 'Keyforge',
    category: 'Gaming',
    price: 3999,
    discountPrice: 2999,
    stock: 61,
    tags: ['mouse', 'gaming', 'wireless'],
    shortDescription: '26K DPI optical sensor in a 58 g shell.',
    description:
      'Weighing just 58 grams with a 26,000 DPI optical sensor and optical switches rated for 100 million clicks. The 2.4 GHz dongle delivers 1 ms polling, and 90 hours of battery means you rarely think about charging.',
    specifications: [
      { key: 'Sensor', value: '26,000 DPI optical' },
      { key: 'Weight', value: '58 g' },
      { key: 'Switches', value: 'Optical, 100M clicks' },
      { key: 'Battery', value: '90 hours' },
      { key: 'Polling', value: '1000 Hz wireless' },
    ],
    variants: [
      { name: colors.black, color: colors.black, stock: 30 },
      { name: colors.white, color: colors.white, stock: 20 },
      { name: colors.red, color: colors.red, stock: 11 },
    ],
  },
  {
    name: 'Studio 4K Webcam',
    brand: 'Lumen',
    category: 'Cameras',
    price: 9999,
    discountPrice: 7999,
    stock: 18,
    tags: ['webcam', 'camera', 'streaming'],
    isNewArrival: true,
    shortDescription: '4K30 sensor with on-device HDR and dual mics.',
    description:
      'A 1/2.8" Sony STARVIS sensor with f/1.8 glass delivers clean images even in dim rooms. On-device HDR keeps windows from blowing out, and the dual noise-cancelling mics use beamforming to focus on your voice.',
    specifications: [
      { key: 'Resolution', value: '4K30 / 1080p60' },
      { key: 'Sensor', value: '1/2.8" Sony STARVIS' },
      { key: 'Lens', value: 'f/1.8 glass, 90° FOV' },
      { key: 'Audio', value: 'Dual beamforming mics' },
      { key: 'Mount', value: 'Magnetic privacy shutter + tripod thread' },
    ],
  },
  {
    name: 'Lumen Creator Tripod Kit',
    brand: 'Lumen',
    category: 'Cameras',
    price: 3499,
    discountPrice: 0,
    stock: 33,
    tags: ['tripod', 'camera', 'vlog'],
    shortDescription: 'Carbon-fibre travel tripod with ball head.',
    description:
      'Weighs 1.1 kg but holds 8 kg. The 5-section carbon legs lock with a quarter turn, and the included ball head has a separate panning lock plus an Arca-Swiss plate for quick swaps.',
    specifications: [
      { key: 'Max height', value: '165 cm' },
      { key: 'Folded length', value: '38 cm' },
      { key: 'Load capacity', value: '8 kg' },
      { key: 'Weight', value: '1.1 kg' },
    ],
  },
  {
    name: 'Everyday Oxford Shirt',
    brand: 'Northbound',
    category: 'Fashion',
    price: 2499,
    discountPrice: 1749,
    stock: 120,
    tags: ['shirt', 'oxford', 'menswear', 'cotton'],
    badges: ['Best Seller'],
    isFeatured: true,
    shortDescription: 'Garment-washed organic cotton oxford.',
    description:
      'Cut from 140 gsm organic cotton oxford and garment washed for a broken-in feel from the first wear. A touch of elastane keeps the shoulders moving, and the button-down collar holds its roll all day.',
    specifications: [
      { key: 'Fabric', value: '98% organic cotton, 2% elastane' },
      { key: 'Fit', value: 'Regular, slightly tapered waist' },
      { key: 'Weight', value: '140 gsm' },
      { key: 'Care', value: 'Machine wash cold, tumble dry low' },
    ],
    variants: [
      { name: 'White / S', size: 'S', color: colors.white, stock: 18 },
      { name: 'White / M', size: 'M', color: colors.white, stock: 24 },
      { name: 'White / L', size: 'L', color: colors.white, stock: 20 },
      { name: 'White / XL', size: 'XL', color: colors.white, stock: 14 },
      { name: 'Cobalt / M', size: 'M', color: colors.blue, stock: 16 },
      { name: 'Cobalt / L', size: 'L', color: colors.blue, stock: 12 },
    ],
  },
  {
    name: 'Trail Runner Sneakers',
    brand: 'Kinetiq',
    category: 'Fashion',
    price: 6499,
    discountPrice: 4999,
    stock: 74,
    tags: ['shoes', 'sneakers', 'running', 'trail'],
    isFeatured: true,
    shortDescription: 'Rock-plated grip with responsive foam midsole.',
    description:
      'A 4 mm multi-directional lug pattern bites into loose gravel while the nitrogen-infused foam midsole returns energy on climbs. The knitted upper uses recycled yarn and drains fast after stream crossings.',
    specifications: [
      { key: 'Drop', value: '6 mm' },
      { key: 'Weight', value: '272 g (UK 9)' },
      { key: 'Outsole', value: 'Vibram Megagrip, 4 mm lugs' },
      { key: 'Upper', value: 'Recycled knit with TPU overlays' },
    ],
    variants: [
      { name: 'Crimson / UK 7', size: 'UK 7', color: colors.red, stock: 12 },
      { name: 'Crimson / UK 8', size: 'UK 8', color: colors.red, stock: 15 },
      { name: 'Crimson / UK 9', size: 'UK 9', color: colors.red, stock: 16 },
      { name: 'Crimson / UK 10', size: 'UK 10', color: colors.red, stock: 11 },
      { name: 'Black / UK 9', size: 'UK 9', color: colors.black, stock: 20 },
    ],
  },
  {
    name: 'Merino Crew Sweater',
    brand: 'Northbound',
    category: 'Fashion',
    price: 4999,
    discountPrice: 3499,
    stock: 48,
    tags: ['sweater', 'merino', 'wool', 'winter'],
    shortDescription: '17.5 micron merino, naturally temperature regulating.',
    description:
      'Spun from 17.5 micron merino so it sits softly against skin without an itch. Merino regulates temperature and resists odour, which makes this crew a genuine week-long travel piece. Fully fashioned shoulders prevent sag.',
    specifications: [
      { key: 'Material', value: '100% merino wool (mulesing-free)' },
      { key: 'Gauge', value: '12-gauge knit' },
      { key: 'Care', value: 'Hand wash cool, dry flat' },
    ],
    variants: [
      { name: 'Forest / M', size: 'M', color: colors.green, stock: 14 },
      { name: 'Forest / L', size: 'L', color: colors.green, stock: 12 },
      { name: 'Graphite / M', size: 'M', color: colors.grey, stock: 12 },
      { name: 'Graphite / L', size: 'L', color: colors.grey, stock: 10 },
    ],
  },
  {
    name: 'Canvas Weekender Duffel',
    brand: 'Carryon Co.',
    category: 'Fashion',
    price: 5999,
    discountPrice: 4499,
    stock: 26,
    tags: ['bag', 'travel', 'duffel', 'canvas'],
    isNewArrival: true,
    shortDescription: 'Waxed canvas, full-grain leather trim, cabin legal.',
    description:
      '24 oz waxed canvas shrugs off rain while the full-grain leather handles soften with use. A separate base compartment takes shoes or wet kit, and the whole bag fits within cabin limits for most carriers.',
    specifications: [
      { key: 'Capacity', value: '42 L' },
      { key: 'Material', value: '24 oz waxed canvas, full-grain leather' },
      { key: 'Dimensions', value: '55 x 30 x 25 cm' },
      { key: 'Warranty', value: 'Lifetime hardware warranty' },
    ],
    variants: [
      { name: 'Desert Sand', color: colors.sand, stock: 12 },
      { name: 'Navy', color: colors.navy, stock: 14 },
    ],
  },
  {
    name: 'Ceramic Pour-Over Coffee Set',
    brand: 'Terra',
    category: 'Home & Living',
    price: 3299,
    discountPrice: 2499,
    stock: 64,
    tags: ['coffee', 'kitchen', 'ceramic', 'pour-over'],
    isFeatured: true,
    shortDescription: 'Hand-thrown dripper, server and two cups.',
    description:
      'Each piece is hand-thrown from stoneware clay and finished in a matte reactive glaze, so no two sets are identical. The 60° cone with three extraction holes produces a clean, sweet cup; the server doubles as a 600 ml carafe.',
    specifications: [
      { key: 'Includes', value: 'Dripper, 600 ml server, 2 x 220 ml cups' },
      { key: 'Material', value: 'Stoneware, lead-free reactive glaze' },
      { key: 'Filter', value: 'Standard #02 cone filters' },
      { key: 'Care', value: 'Dishwasher safe' },
    ],
  },
  {
    name: 'Linen Bedding Set',
    brand: 'Terra',
    category: 'Home & Living',
    price: 7999,
    discountPrice: 5999,
    stock: 38,
    tags: ['bedding', 'linen', 'home'],
    shortDescription: 'Stonewashed French flax that softens every wash.',
    description:
      'Woven from European flax and stonewashed twice, this set breathes in summer and insulates in winter. Includes a duvet cover with interior ties and two pillowcases with envelope closures.',
    specifications: [
      { key: 'Material', value: '100% French flax linen, 165 gsm' },
      { key: 'Includes', value: 'Duvet cover + 2 pillowcases' },
      { key: 'Certification', value: 'OEKO-TEX Standard 100' },
    ],
    variants: [
      { name: 'Double / Arctic White', size: 'Double', color: colors.white, stock: 14 },
      { name: 'Queen / Desert Sand', size: 'Queen', color: colors.sand, stock: 12 },
      { name: 'King / Forest Green', size: 'King', color: colors.green, stock: 12 },
    ],
  },
  {
    name: 'Terracotta Scented Candle Trio',
    brand: 'Ember & Oak',
    category: 'Home & Living',
    price: 1899,
    discountPrice: 1499,
    stock: 90,
    tags: ['candle', 'home', 'fragrance', 'gift'],
    shortDescription: 'Coconut-soy wax, 45-hour burn each, reusable pots.',
    description:
      'Poured in small batches with a coconut-soy blend and a cotton wick for a clean, even burn. Notes of smoked cedar, fig leaf and vetiver; the terracotta pots make excellent pen cups afterwards.',
    specifications: [
      { key: 'Weight', value: '3 x 180 g' },
      { key: 'Burn time', value: '~45 hours each' },
      { key: 'Wax', value: 'Coconut-soy blend, cotton wick' },
      { key: 'Fragrance', value: 'Cedarwood, fig leaf, vetiver' },
    ],
  },
  {
    name: 'Cold Brew Glass Carafe',
    brand: 'Terra',
    category: 'Home & Living',
    price: 2299,
    discountPrice: 0,
    stock: 0,
    tags: ['coffee', 'kitchen', 'cold brew'],
    shortDescription: '1 L borosilicate carafe with stainless filter.',
    description:
      'Borosilicate glass resists thermal shock while the laser-etched stainless filter keeps silt out of your cup without paper. Steep overnight for a low-acid concentrate that keeps for a week in the fridge.',
    specifications: [
      { key: 'Capacity', value: '1 litre' },
      { key: 'Material', value: 'Borosilicate glass, 304 stainless' },
      { key: 'Care', value: 'All parts dishwasher safe' },
    ],
  },
  {
    name: 'Vitamin C 15% Brightening Serum',
    brand: 'Lumière',
    category: 'Beauty & Care',
    price: 2199,
    discountPrice: 1649,
    stock: 130,
    tags: ['skincare', 'serum', 'vitamin c'],
    badges: ['Best Seller'],
    isFeatured: true,
    shortDescription: 'Stabilised THD ascorbate with ferulic acid.',
    description:
      'Uses tetrahexyldecyl ascorbate, a stable oil-soluble form of vitamin C that penetrates deeper without the sting of L-ascorbic acid. Ferulic acid and vitamin E extend antioxidant activity; the airless pump protects the formula from oxidising.',
    specifications: [
      { key: 'Size', value: '30 ml' },
      { key: 'Key actives', value: '15% THD ascorbate, 0.5% ferulic acid' },
      { key: 'Free from', value: 'Fragrance, essential oils, silicones' },
      { key: 'Skin type', value: 'All, including sensitive' },
    ],
  },
  {
    name: 'Hydrating Ceramide Moisturiser',
    brand: 'Lumière',
    category: 'Beauty & Care',
    price: 1699,
    discountPrice: 1299,
    stock: 145,
    tags: ['skincare', 'moisturiser', 'ceramide'],
    shortDescription: 'Barrier-repair cream with 5 ceramides and squalane.',
    description:
      'A fragrance-free cream built around the skin barrier: five ceramides in physiological ratio, cholesterol, squalane and panthenol. Non-comedogenic and light enough for daytime under sunscreen.',
    specifications: [
      { key: 'Size', value: '50 ml' },
      { key: 'Key actives', value: 'Ceramide NP/AP/EOP, squalane, panthenol' },
      { key: 'Texture', value: 'Rich cream, fast absorbing' },
    ],
  },
  {
    name: 'Salon Repair Shampoo Bar',
    brand: 'Ember & Oak',
    category: 'Beauty & Care',
    price: 999,
    discountPrice: 749,
    stock: 210,
    tags: ['haircare', 'shampoo', 'sustainable'],
    isNewArrival: true,
    shortDescription: 'One bar replaces three bottles of shampoo.',
    description:
      'A pH-balanced syndet bar with hydrolysed rice protein and murumuru butter. Lathers richly in hard water, lasts 80+ washes, and ships in a compostable paper sleeve with no plastic.',
    specifications: [
      { key: 'Weight', value: '90 g (~80 washes)' },
      { key: 'Hair type', value: 'All, colour-safe' },
      { key: 'Packaging', value: 'Plastic-free, compostable' },
    ],
  },
  {
    name: 'Pro Yoga Mat 6mm',
    brand: 'Kinetiq',
    category: 'Sports & Outdoors',
    price: 3499,
    discountPrice: 2699,
    stock: 58,
    tags: ['yoga', 'fitness', 'mat'],
    shortDescription: 'Closed-cell natural rubber with alignment lines.',
    description:
      'Natural tree rubber base grips harder as you sweat, and the 6 mm closed-cell top means sweat does not soak in. Laser-etched alignment lines help you square your stance without looking up.',
    specifications: [
      { key: 'Dimensions', value: '183 x 66 cm, 6 mm' },
      { key: 'Material', value: 'Natural rubber + PU top' },
      { key: 'Weight', value: '2.4 kg' },
    ],
    variants: [
      { name: 'Forest Green', color: colors.green, stock: 22 },
      { name: 'Graphite Grey', color: colors.grey, stock: 20 },
      { name: 'Desert Sand', color: colors.sand, stock: 16 },
    ],
  },
  {
    name: 'Adjustable Dumbbell Pair 2x24kg',
    brand: 'Ironcore',
    category: 'Sports & Outdoors',
    price: 21999,
    discountPrice: 17999,
    stock: 12,
    tags: ['fitness', 'dumbbell', 'strength', 'home gym'],
    isFeatured: true,
    shortDescription: 'Dial from 2.5 kg to 24 kg in one turn.',
    description:
      'Replaces 15 pairs of dumbbells. The dial mechanism locks plates securely with a metal-on-metal ratchet, and the moulded cradle keeps plates aligned between sets. Sold as a pair with a storage tray.',
    specifications: [
      { key: 'Range', value: '2.5 - 24 kg per dumbbell' },
      { key: 'Increments', value: '2.5 kg' },
      { key: 'Handle', value: 'Knurled steel, 34 mm' },
      { key: 'Includes', value: '2 dumbbells + 2 storage trays' },
    ],
  },
  {
    name: 'Insulated Trail Bottle 1L',
    brand: 'Ironcore',
    category: 'Sports & Outdoors',
    price: 1499,
    discountPrice: 1099,
    stock: 160,
    tags: ['bottle', 'hydration', 'outdoors'],
    shortDescription: 'Triple-wall vacuum steel, 24 h cold / 12 h hot.',
    description:
      '18/8 stainless steel with a triple-wall vacuum layer keeps drinks cold for 24 hours and hot for 12. The powder-coated exterior stays grippy when wet and the leak-proof cap has a fold-out carry loop.',
    specifications: [
      { key: 'Capacity', value: '1000 ml' },
      { key: 'Material', value: '18/8 stainless steel' },
      { key: 'Retention', value: '24 h cold, 12 h hot' },
    ],
    variants: [
      { name: 'Midnight Black', color: colors.black, stock: 60 },
      { name: 'Arctic White', color: colors.white, stock: 55 },
      { name: 'Cobalt Blue', color: colors.blue, stock: 45 },
    ],
  },
  {
    name: 'The Design of Everyday Systems',
    brand: 'Folio Press',
    category: 'Books & Stationery',
    price: 1299,
    discountPrice: 999,
    stock: 85,
    tags: ['book', 'design', 'non-fiction'],
    isNewArrival: true,
    shortDescription: 'A practitioner\'s guide to building products that last.',
    description:
      'Part handbook, part memoir from two decades of shipping software. Covers system design, decision-making under uncertainty and the craft of writing interfaces that explain themselves. 384 pages with 60 hand-drawn diagrams.',
    specifications: [
      { key: 'Format', value: 'Hardcover, 384 pages' },
      { key: 'Publisher', value: 'Folio Press' },
      { key: 'ISBN', value: '978-93-81234-56-7' },
      { key: 'Language', value: 'English' },
    ],
  },
  {
    name: 'Dot Grid Notebook Set (3 Pack)',
    brand: 'Folio Press',
    category: 'Books & Stationery',
    price: 899,
    discountPrice: 649,
    stock: 240,
    tags: ['notebook', 'stationery', 'journaling'],
    shortDescription: '160 gsm fountain-pen-friendly paper, lay-flat binding.',
    description:
      '160 gsm paper handles fountain pens, markers and highlighters without ghosting. The sewn lay-flat binding opens completely, and each A5 book carries 160 numbered dot-grid pages with a ribbon marker.',
    specifications: [
      { key: 'Size', value: 'A5 (148 x 210 mm)' },
      { key: 'Paper', value: '160 gsm, dotted 5 mm grid' },
      { key: 'Pages', value: '160 per book' },
      { key: 'Binding', value: 'Sewn lay-flat hardcover' },
    ],
  },
  {
    name: 'Insight Fountain Pen',
    brand: 'Folio Press',
    category: 'Books & Stationery',
    price: 2999,
    discountPrice: 2399,
    stock: 47,
    tags: ['pen', 'fountain pen', 'stationery'],
    shortDescription: 'Brass body with a German medium nib.',
    description:
      'A solid brass barrel develops a unique patina with use. The German-made stainless nib writes with a smooth, wet line out of the box, and the converter accepts any standard international cartridge.',
    specifications: [
      { key: 'Nib', value: 'Stainless steel, medium' },
      { key: 'Body', value: 'Solid brass, lacquer finish' },
      { key: 'Filling', value: 'Converter or international cartridges' },
      { key: 'Weight', value: '38 g' },
    ],
    variants: [
      { name: 'Fine nib', size: 'Fine', stock: 15 },
      { name: 'Medium nib', size: 'Medium', stock: 18 },
      { name: 'Broad nib', size: 'Broad', stock: 14 },
    ],
  },
  {
    name: 'Nova Console Controller',
    brand: 'Keyforge',
    category: 'Gaming',
    price: 6999,
    discountPrice: 5499,
    stock: 36,
    tags: ['controller', 'gaming', 'console'],
    isFeatured: true,
    shortDescription: 'Hall-effect sticks that never drift.',
    description:
      'Hall-effect magnetic sticks eliminate drift permanently, and the back paddles can be remapped on the fly without software. Trigger stops swap between racing and shooter modes with a flick.',
    specifications: [
      { key: 'Sticks', value: 'Hall-effect, anti-drift' },
      { key: 'Battery', value: '35 hours' },
      { key: 'Extras', value: '4 remappable back buttons, trigger stops' },
      { key: 'Compatibility', value: 'PC, Android, Switch' },
    ],
    variants: [
      { name: colors.black, color: colors.black, stock: 18 },
      { name: colors.white, color: colors.white, stock: 18 },
    ],
  },
  {
    name: 'Stream Deck Mini Controller',
    brand: 'Lumen',
    category: 'Gaming',
    price: 11999,
    discountPrice: 9999,
    stock: 21,
    tags: ['streaming', 'desk', 'controller'],
    shortDescription: 'Six LCD keys for scenes, macros and shortcuts.',
    description:
      'Six customisable LCD keys trigger scenes, launch apps or fire multi-step macros. Drag icons straight onto keys with the companion app, and build nested folders for unlimited actions.',
    specifications: [
      { key: 'Keys', value: '6 LCD, 72 x 72 px' },
      { key: 'Connection', value: 'USB-C' },
      { key: 'Software', value: 'Windows, macOS' },
    ],
  },
  {
    name: 'Aeon Noise Cancelling Earbuds',
    brand: 'Auralis',
    category: 'Electronics',
    price: 6999,
    discountPrice: 5499,
    stock: 68,
    tags: ['earbuds', 'audio', 'anc', 'tws'],
    isNewArrival: true,
    shortDescription: 'Adaptive ANC with 36-hour total playtime.',
    description:
      'Dual-driver architecture separates bass from mids for a wide, airy stage. Adaptive ANC reacts to your environment, transparency mode pipes the world back in, and the case adds 28 hours on top of the 8 in the buds.',
    specifications: [
      { key: 'Drivers', value: 'Dual (10 mm + 6 mm)' },
      { key: 'Battery', value: '8 h buds + 28 h case' },
      { key: 'ANC', value: 'Adaptive hybrid, 48 dB' },
      { key: 'Rating', value: 'IPX5' },
    ],
    variants: [
      { name: colors.black, color: colors.black, stock: 28 },
      { name: colors.white, color: colors.white, stock: 22 },
      { name: 'Lilac', color: 'Lilac', stock: 18 },
    ],
  },
  {
    name: 'Aero Desk Lamp Pro',
    brand: 'Terra',
    category: 'Home & Living',
    price: 4499,
    discountPrice: 3499,
    stock: 44,
    tags: ['lamp', 'lighting', 'desk', 'home office'],
    shortDescription: 'Flicker-free CRI 97 light with wireless charging base.',
    description:
      'A diffusion panel renders colour at CRI 97 with no visible flicker, so video calls and paper work both look right. The base charges a phone wirelessly, and the arm sweeps through 120° of travel without sagging.',
    specifications: [
      { key: 'CRI', value: '97 (flicker-free, TÜV certified)' },
      { key: 'Colour temp', value: '2700K - 6500K adjustable' },
      { key: 'Charging pad', value: '15 W Qi wireless' },
      { key: 'Power', value: 'USB-C, 18 W' },
    ],
  },
  {
    name: 'Weighted Throw Blanket 7kg',
    brand: 'Ember & Oak',
    category: 'Home & Living',
    price: 4999,
    discountPrice: 3999,
    stock: 52,
    tags: ['blanket', 'home', 'sleep', 'wellness'],
    shortDescription: 'Glass-bead weighted throw in washed cotton.',
    description:
      'Micro glass beads sit in a 7x7 grid of stitched channels so weight stays evenly distributed and never bunches. The washed cotton cover is breathable on warm nights and removable for washing at 30°C.',
    specifications: [
      { key: 'Weight', value: '7 kg (recommended for 60-80 kg adults)' },
      { key: 'Size', value: '150 x 200 cm' },
      { key: 'Material', value: 'Washed cotton + micro glass beads' },
      { key: 'Care', value: 'Cover machine washable' },
    ],
  },
  {
    name: 'Reflex Boxing Gloves 16oz',
    brand: 'Ironcore',
    category: 'Sports & Outdoors',
    price: 4299,
    discountPrice: 3299,
    stock: 40,
    tags: ['boxing', 'fitness', 'gloves'],
    shortDescription: 'Layered IMF foam with a locked wrist strap.',
    description:
      'Three layers of impact foam absorb heavy bag sessions without bottoming out. The long hook-and-loop strap locks the wrist in a neutral angle to protect against strains, and the mesh palm keeps hands dry.',
    specifications: [
      { key: 'Weight', value: '16 oz (also stocked in 12 oz)' },
      { key: 'Padding', value: 'Triple-layer IMF foam' },
      { key: 'Material', value: 'Engineered leather' },
    ],
    variants: [
      { name: '12 oz / Crimson', size: '12oz', color: colors.red, stock: 14 },
      { name: '16 oz / Crimson', size: '16oz', color: colors.red, stock: 14 },
      { name: '16 oz / Black', size: '16oz', color: colors.black, stock: 12 },
    ],
  },
];

/** Demo coupons. */
const coupons = [
  { code: 'WELCOME10', description: '10% off your first order', type: 'percentage', value: 10, maxDiscount: 500, minOrderValue: 999, usageLimit: 0, perUserLimit: 1 },
  { code: 'SAVE500', description: 'Flat ₹500 off orders above ₹4,999', type: 'fixed', value: 500, minOrderValue: 4999, usageLimit: 500, perUserLimit: 1 },
  { code: 'FESTIVE25', description: '25% off, capped at ₹2,000', type: 'percentage', value: 25, maxDiscount: 2000, minOrderValue: 2999, usageLimit: 200, perUserLimit: 1 },
  { code: 'FREESHIP', description: 'Extra ₹99 off - effectively free shipping', type: 'fixed', value: 99, minOrderValue: 499, usageLimit: 0, perUserLimit: 3 },
];

module.exports = { categories, products, coupons };
